import Head from 'next/head'
import Header from 

export default function Home() {
  return (
    <div>
      <Head>
        <title>Powpa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi</h1>
      <Header/>
    </div>
  )
}
